settings:
  log_level: "DEBUG"
  parquet_compression: "gzip"

files:
  input_dir: "assets"
  input_file: "weapons-wanted.json"
  
  output_dir: "assets"
  output_file: "ua-mia-weapons.parquet.gzip"

regex_mappings:
  oblasts: 
    "Uzhhorod": '(?i)\bЗАКАРПАТ\w{0,6}.{1,5}\bобл'
    "Lviv": '(?i)\bЛЬВ[іо]ВС\w{0,1}К\w{0,6}.{1,5}\bобл'
    "Ivano-Frankivsk": '(?i)\b[іи]В\w{0,3}[.\-]ФР\w{0,10}.{1,5}\bобл'
    "Chernivtsi": '(?i)\bЧЕРН[іо]В\w{0,1}Ц\w{0,6}.{1,5}\bобл'
    "Ternopil": '(?i)\bТЕРНОП[іо]ЛЬС\w{0,6}.{1,5}\bобл'
    "Lutsk": '(?i)\bВОЛ\w{1,2}Н\w{0,6}.{1,5}\bобл'
    "Rivne": '(?i)\bР[іо]ВНЕНС\w{0,6}.{1,5}\bобл'
    "Zhytomyr": '(?i)\bЖИТОМИРС\w{0,6}.{1,5}\bобл'
    "Khmelnytskyi": '(?i)\bХМЕЛЬНИЦ\w{0,6}.{1,5}\bобл'
    "Vinnytsia": '(?i)\bВ[іи]ННИЦ\w{0,6}.{1,5}\bобл'
    "Kyiv": '(?i)\bКИ[їе]В\w{0,6}.{1,5}\bобл'
    "Cherkasy": '(?i)\bЧЕРКАC\w{0,6}.{1,5}\bобл'
    "Kropyvnytskyi": '(?i)\bК[іи]РОВОГРАДС\w{0,6}.{1,5}\bобл'
    "Odesa": '(?i)\bОДЕС\w{0,6}.{1,5}\bобл'
    "Mykolaiv": '(?i)\b[мн]ИКОЛА[їеє]ВС\w{0,6}.{1,5}\bобл'
    "Kherson": '(?i)\bХЕРСОНС\w{0,6}.{1,5}\bобл'
    "Simferopol": '(?i)\bКР\w{1,2}М\b|\bСЕВАСТ\w{0,1}ПОЛ\w{1,10}\b|\bЯЛТ\w{1,10}|\bАР\b|\bС[іи]МФЕРОПОЛ\w{1,10}\b'
    "Zaporizhzhia": '(?i)\bЗАПОР[іо]\w{0,6}.{1,5}\bобл'
    "Dnipro": '(?i)\bДН[іе]ПРОПЕТРОВС\w{0,6}.{1,5}\bобл'
    "Poltava": '(?i)\bПОЛТАВС\w{0,6}.{1,5}\bобл'
    "Chernihiv": '(?i)\bЧЕРН[іи]Г[іо]В\w{0,6}.{1,5}\bобл'
    "Sumy": '(?i)\bСУМ\w{0,6}.{1,5}\bобл'
    "Kharkiv": '(?i)\bХАР\w{0,1}К[іо]В\w{0,6}.{1,5}\bобл'
    "Luhansk": '(?i)\bЛУГАНС\w{0,6}.{1,5}\bобл'
    "Donetsk": '(?i)\bДОНЕЦ\w{0,6}.{1,5}\bобл'
  
  adjustments:
    "Uzhhorod": '(?i)\bУЖГОРОД\w{0,6}\b'
    "Lviv": '(?i)\bЛЬВ[іо]В\w{0,6}\b'
    "Ivano-Frankivsk": '(?i)\b[іи]В\w{0,3}[.\-]ФРАНК\w{0,3}ВС\w{0,6}\b'
    "Chernivtsi": '(?i)\bЧЕРН[іо]В\w{0,1}Ц\w{0,6}\b'
    "Ternopil": '(?i)\bТЕРНОП[іо]ЛЬ\w{0,6}\b'
    "Lutsk": '(?i)\bВОЛ\w{1,2}Н\w{0,6}\b|\bЛУЦ\w{0,1}К\w{0,6}\b'
    "Rivne": '(?i)\bР[іо]ВН[ео]\w{0,6}\b|\bГОЩАНС\w{0,5}\b'
    "Zhytomyr": '(?i)\bЖИТОМИР\w{0,6}\b'
    "Khmelnytskyi": '(?i)\bХМЕЛЬНИЦ\w{0,6}\b'
    "Vinnytsia": '(?i)\bВ[іи]ННИЦ\w{0,6}\b'
    "Kyiv": '(?i)\bКИ[їеє]В\w{0,6}\b|\bПЕЧЕРСЬК\w{0,6}\b|\bГОЛОСІЇВ\w{0,6}\b'
    "Cherkasy": '(?i)\bЧЕРКАС\w{0,6}\b'
    "Kropyvnytskyi": '(?i)\bК[іи]РОВОГРАД\w{0,6}\b|\bКРОПИВНИЦ\w{0,6}\b'
    "Odesa": '(?i)\bОДЕС\w{0,6}\b'
    "Mykolaiv": '(?i)\b[мн]ИКОЛА[їеє]В\w{0,6}\b'
    "Kherson": '(?i)\bХЕРСОН\w{0,6}\b'
    "Simferopol": '(?i)\bКР\w{1,2}М\b|\bСЕВАСТ\w{0,1}ПОЛ\w{1,10}\b|\bЯЛТ\w{1,10}|\bАР\b|\bС[іи]МФЕРОПОЛ\w{1,10}\b'
    "Zaporizhzhia": '(?i)\bЗАПОР[іо]\w{0,6}\b'
    "Dnipro": '(?i)\bДН[іе]ПР\w{0,10}\b|\bДН[іе]ПРОПЕТРОВС\w{0,6}\b|\bКРИВ\w{0,3}\W{0,5}Р\w{1,6}\b'
    "Poltava": '(?i)\bПОЛТАВ\w{0,6}\b'
    "Chernihiv": '(?i)\bЧЕРН[іи]Г[іо]В\w{0,6}\b|\bН[іе]ЖИН\w{0,6}\b|\bБАХМА\w{0,6}\b'
    "Sumy": '(?i)\bСУМ\w{0,6}\b|\bЛЮБОТ\w{1,6}\b'
    "Kharkiv": '(?i)\bХАР\w{0,1}К[іо]В\w{0,6}\b|\bЛОЗОВ\w{0,6}\b|\bОСНОВ\w{0,6}\b'
    "Luhansk": '(?i)\bЛУГАНС\w{0,6}\b'
    "Donetsk": '(?i)\bДОНЕЦ\w{0,6}\b'

weapon_mappings:
  bladed:
    "Bladed":
      - "КИНДЖАЛ"
      - "КОРТИК"
      - "МЕЧ"
      - "НІЖ МИСЛИВСЬКИЙ"
      - "НІЖ"
      - "ШАБЛЯ"
      - "ШАШКА"
      - "ШТИК НІЖ"
      - "ШТИК"
  
  handguns:
    "Handguns":
      - "ПІСТОЛЕТ ГАЗОВИЙ"
      - "ПІСТОЛЕТ КУЛЕМЕТ"
      - "ПІСТОЛЕТ МК"
      - "ПІСТОЛЕТ ПІД ГУМОВУ КУЛЮ"
      - "ПІСТОЛЕТ САМОРОБНИЙ"
      - "ПІСТОЛЕТ СИГНАЛЬНИЙ"
      - "ПІСТОЛЕТ СТАРТОВИЙ"
      - "ПІСТОЛЕТ"
      - "РЕВОЛЬВЕР ГАЗОВИЙ"
      - "РЕВОЛЬВЕР ГАЗОВОДРОБОВИЙ"
      - "РЕВОЛЬВЕР ПІД ГУМОВУ КУЛЮ"
      - "РЕВОЛЬВЕР СИГНАЛЬНИЙ"
      - "РЕВОЛЬВЕР СТАРТОВИЙ"
      - "РЕВОЛЬВЕР"
      - "ПІСТОЛЕТ АВТОРУЧКА"

  lfirearms:  
    "Light firearms":
      - "АВТОМАТ"
      - "ГВИНТІВКА МК"
      - "ГВИНТІВКА"
      - "КАРАБІН"
      - "ОБРІЗ ГВИНТІВКИ МК"
      - "ОБРІЗ ГВИНТІВКИ"
      - "ОБРІЗ КАРАБІНА"
      - "ОБРІЗ РУШНИЦІ"
      - "РУШНИЦЯ ЗБІРНА"
      - "РУШНИЦЯ МИСЛИВСЬКА"
      - "РУШНИЦЯ ПОМПОВА"
      - "РУШНИЦЯ"
    
  hfirearms:
    "Heavy firearms":
      - "ГАРМАТА АВТОМАТИЧНА"
      - "ГАРМАТА"
      - "КУЛЕМЕТ СТАНКОВИЙ"
      - "КУЛЕМЕТ"
      - "РУШНИЦЯ ПРОТИТАНКОВА"
  
  pneumaticflob:
    "Pneumatic&Flobert":
      - "ГВИНТІВКА ПНЕВМАТИЧНА"
      - "КАРАБІН ПІД ПАТРОН ФЛОБЕРА"
      - "ПІСТОЛЕТ ПІД ПАТРОН ФЛОБЕРА"
      - "ПІСТОЛЕТ ПНЕВМАТИЧНИЙ"
      - "РЕВОЛЬВЕР ПІД ПАТРОН ФЛОБЕРА"
      - "РЕВОЛЬВЕР ПНЕВМАТИЧНИЙ"
    
  artillery:
    "Artillery":
      - "ГРАНАТОМЕТ"
      - "МІНОМЕТ"
      - "ПЗРК"
      - "ПТРК"
      - "РАКЕТНИЦЯ"
      - "ПУСКОВІ УСТАНОВКИ"
      - "ЗЕНІТНА УСТАНОВКА"
    
  explosives:
    "Explosives":
      - "ВИБУХОВІ РЕЧОВИНИ"
      - "ГРАНАТА"
      - "РАКЕТА"
      - "СНАРЯД"
  
  other:
    "Other":
      - "ДЕТАЛІ"
      - "ЗАПАЛ"
      - "ЗАТВОР ДЕТАЛЬ"
      - "ІНШІ ДЕТАЛІ ЗБРОЇ"
      - "МАГАЗИН ПІСТОЛЕТНИЙ"
      - "МАГАЗИН"
      - "НАБОЇ БОЄВІ"
      - "ПРИЦІЛ ОПТИЧНИЙ"
      - "РАМКА ДЕТАЛЬ"
      - "СТВОЛ ДЕТАЛЬ"
      - "СТВОЛЬНА КОРОБКА ДЕТАЛЬ"
      - "АРБАЛЕТ"
      - "РУШНИЦЯ ДЛЯ ПІДВОДНОГО ПОЛЮВАННЯ"
      - "АВТОМАТ УЧБОВИЙ"
      - "ГВИНТІВКА УЧБОВА"
      - "КАРАБІН УЧБОВИЙ"
      - "КУЛЕМЕТ УЧБОВИЙ"
      - "ПІСТОЛЕТ МОНТАЖНИЙ"
      - "ПІСТОЛЕТ УЧБОВИЙ"
      - "КИСТЕНЬ"