from .regions import generate_rank_region_population
from .regions import generate_region_total_linechart
from .regions import generate_region_weapons_polarchart
from .regions import generate_region_report_10y_linechart

from .piechart import generate_reports_piechart
from .scatterplot import generate_reports_scatterplot
from .scatterplot import generate_weapons_scatterplot
from .barchart import generate_events_barchart
from .table import generate_region_total_table
from .table import generate_weaponcategory_total_table