from .scattertable import scatter_table
from .regstats import region_population_end2021
from .regstats import region_total_end2021
from .regstats import region_yr_totals_linegarph
from .regstats import region_maxmin
from .regstats import region_yr_totals_linegrph2012
from .regstats import region_rank_total
from .regstats import region_total
from .regstats import region_theftloss_piechart
from .regstats import region_theftloss_totals
from .wscats import yr_weekly_scats
from .histogram import main_hist
from .top5 import top_5
from .hbarwep import hbar_wep
from .tlsratio import tls_ratio