name: Import Data

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 */1 *'

jobs:
  download-json:
    runs-on: ubuntu-latest
    steps:
      
      - name: download json file
        run: |
          dir

      - name: archive json file
        uses: actions/upload-artifact@v3
        with:
          name: weapons-json-artifact
          path: mia-ua-weapons/assets/weapons-wanted.json
          if-no-files-found: error

  clean-data:
    runs-on: ubuntu-latest
    needs: download-json
    steps:

      - name: download json artifact
        uses: actions/download-artifact@v3
        with:
          name: weapons-json-artifact
          path: mia-ua-weapons/assets

      - name: checkout repo content
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          cd mia-ua-weapons
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: python pipeline.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "Updated main dataset" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
